### ISSUE TITLE
runpod error

### ISSUE THREAD

**Issue by KittenYang** [ashleykleynhans/facefusion-docker#1]
Hi sir, I deploy the docker but error outputs like that:
<img width="626" alt="Screenshot 2023-08-31 at 11 48 22" src="https://github.com/ashleykleynhans/facefusion-docker/assets/5517281/e65fe72a-e537-4ecc-8b21-9a23f743cbff">

**Comment by ashleykleynhans** [comment]
This can't really work on RunPod anyway because the Cloudflare timeout of 100 seconds is too low for the video to complete processing so I don't recommend running this on RunPod.
