### ISSUE TITLE
How you access it on runpod? 

### ISSUE THREAD

**Issue by cantonalex** [ashleykleynhans/facefusion-docker#7]
Is the gradio interface accessible or is it purely CLI?

**Comment by ashleykleynhans** [comment]
There is a README for a reason, read it instead of wasting peoples time asking stupid and unnecessary questions.

**Comment by cantonalex** [comment]
I literally read it its two lines: 
Available on RunPod
This image is designed to work on [RunPod](https://runpod.io/?ref=2xxro4sy). You can use my custom [RunPod template](https://runpod.io/gsc?template=pxpldkhq6u&ref=2xxro4sy) to launch it on RunPod.

I tried connecting to port 3000: "The port is not up yet"

**Comment by ashleykleynhans** [comment]
Read the logs, there is a 99.9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999% chance that its still syncing to workspace and says please wait, you have to wait, its not magic or something.

**Comment by wraworjirrjeawaweq** [comment]
This was 20 minutes ago..

```
2024-05-16T05:23:33.331148739Z FileZilla SFTP configuration file created at: /workspace/filezilla_sftp_config.xml
2024-05-16T05:23:33.331178732Z Exporting environment variables...
2024-05-16T05:23:33.336363520Z Container is READY!

```
